Update check_jsons.yml to inline json validation check. (#675)
* Update check_jsons.yml to inline json validation check.

* delete script and escape evaluation of filename

diff --git a/.github/workflows/check_jsons.yml b/.github/workflows/check_jsons.yml
--- a/.github/workflows/check_jsons.yml
+++ b/.github/workflows/check_jsons.yml
@@ -1,5 +1,5 @@
 
-name: Python application
+name: JSON Validation
 
 on:
   pull_request:
@@ -21,4 +21,15 @@ jobs:
         python-version: "3.10"
     - name: Validate JSONs
       run: |
-        ./scripts/ci_validate_json_files.sh
+        json_files=$(find . -name "*.json")
+
+        # Validate JSON files
+        for file in $json_files
+        do
+            echo "Validating $file"
+            result=$(python -m json.tool "$file")
+            if [ $? -ne 0 ]; then
+                echo "Invalid JSON file: $file"
+                exit 1
+            fi
+        done
